//---------------------------------------------------------------------
// CascadeSharp
// General Public License V2
//---------------------------------------------------------------------

using System;
using CascadeSharp.TKernel.TCollection;
using CascadeSharp.TKMath.gp;
using CascadeSharp.TKService.Graphic3d;

namespace CascadeSharp.TKV3d.Prs3d
{
    //---------------------------------------------------------------------
    //  Class  Prs3d_Text
    //---------------------------------------------------------------------
    public sealed class Prs3d_Text
    {
        public Prs3d_Text()
            : base()
        {
            throw new NotImplementedException();
        }

        public Prs3d_Text(Prs3d_Text parameter1)
            : base()
        {
            throw new NotImplementedException();
        }

        public Graphic3d_Text Draw(Graphic3d_Group theGroup, Prs3d_TextAspect theAspect,
            TCollection_ExtendedString theText, gp_Pnt theAttachmentPoint)
        {
            throw new NotImplementedException();
        }

        public Graphic3d_Text Draw(Graphic3d_Group theGroup, Prs3d_TextAspect theAspect,
            TCollection_ExtendedString theText, gp_Ax2 theOrientation, bool theHasOwnAnchor)
        {
            throw new NotImplementedException();
        }

        public Graphic3d_Text Draw(Graphic3d_Group theGroup, Prs3d_TextAspect theAspect,
            TCollection_ExtendedString theText, gp_Ax2 theOrientation)
        {
            throw new NotImplementedException();
        }

        public void Draw(Graphic3d_Structure thePrs, Prs3d_Drawer theDrawer, TCollection_ExtendedString theText,
            gp_Pnt theAttachmentPoint)
        {
            throw new NotImplementedException();
        }

        public void Draw(Graphic3d_Structure thePrs, Prs3d_TextAspect theAspect, TCollection_ExtendedString theText,
            gp_Ax2 theOrientation, bool theHasOwnAnchor)
        {
            throw new NotImplementedException();
        }

        public void Draw(Graphic3d_Structure thePrs, Prs3d_TextAspect theAspect, TCollection_ExtendedString theText,
            gp_Ax2 theOrientation)
        {
            throw new NotImplementedException();
        }

        public void Draw(Graphic3d_Structure thePrs, Prs3d_TextAspect theAspect, TCollection_ExtendedString theText,
            gp_Pnt theAttachmentPoint)
        {
            throw new NotImplementedException();
        }
    }; // class Prs3d_Text
}