//---------------------------------------------------------------------
// CascadeSharp
// General Public License V2
//---------------------------------------------------------------------

using System;
using CascadeSharp.TKBRep.TopoDS;
using CascadeSharp.TKernel.Message;

namespace CascadeSharp.TKShHealing.ShapeUpgrade
{
    //---------------------------------------------------------------------
    //  Class  ShapeUpgrade_ShapeConvertToBezier
    //---------------------------------------------------------------------
    public sealed class ShapeUpgrade_ShapeConvertToBezier : ShapeUpgrade_ShapeDivide
    {
        public ShapeUpgrade_ShapeConvertToBezier()
            : base()
        {
            throw new NotImplementedException();
        }

        public ShapeUpgrade_ShapeConvertToBezier(TopoDS_Shape S)
            : base()
        {
            throw new NotImplementedException();
        }

        public ShapeUpgrade_ShapeConvertToBezier(ShapeUpgrade_ShapeConvertToBezier parameter1)
            : base()
        {
            throw new NotImplementedException();
        }

        public void Set2dConversion(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool Get2dConversion()
        {
            throw new NotImplementedException();
        }

        public void Set3dConversion(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool Get3dConversion()
        {
            throw new NotImplementedException();
        }

        public void SetSurfaceConversion(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool GetSurfaceConversion()
        {
            throw new NotImplementedException();
        }

        public void Set3dLineConversion(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool Get3dLineConversion()
        {
            throw new NotImplementedException();
        }

        public void Set3dCircleConversion(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool Get3dCircleConversion()
        {
            throw new NotImplementedException();
        }

        public void Set3dConicConversion(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool Get3dConicConversion()
        {
            throw new NotImplementedException();
        }

        public void SetPlaneMode(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool GetPlaneMode()
        {
            throw new NotImplementedException();
        }

        public void SetRevolutionMode(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool GetRevolutionMode()
        {
            throw new NotImplementedException();
        }

        public void SetExtrusionMode(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool GetExtrusionMode()
        {
            throw new NotImplementedException();
        }

        public void SetBSplineMode(bool mode)
        {
            throw new NotImplementedException();
        }

        public bool GetBSplineMode()
        {
            throw new NotImplementedException();
        }

        public bool Perform(bool newContext)
        {
            throw new NotImplementedException();
        }

        public bool Perform()
        {
            throw new NotImplementedException();
        }

        public ShapeUpgrade_FaceDivide GetSplitFaceTool()
        {
            throw new NotImplementedException();
        }

        public Message_Msg GetFaceMsg()
        {
            throw new NotImplementedException();
        }

        public Message_Msg GetWireMsg()
        {
            throw new NotImplementedException();
        }

        public Message_Msg GetEdgeMsg()
        {
            throw new NotImplementedException();
        }
    }; // class ShapeUpgrade_ShapeConvertToBezier
}